;
; Copyright (c) 2022 Nordic Semiconductor ASA
;
; SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
;

Temp_Component_ID_Elems = [
    'temp',
    UID: bstr,
    Size: bstr .cbor uint,
    Align: bstr .cbor uint,
    ?Context: bstr,
]

Component_ID //= Temp_Component_ID
